version: '3'

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_EXPLORE_ENABLED=true
    ports:
      - 3000:3000
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports: 
      - 3100:3100
    volumes: 
      - .:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml

  prometheus:
    image: prom/prometheus:v2.46.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

    command: "--config.file=/etc/prometheus/prometheus.yaml"
